spring.application.name=demo1

project.name=Sample Project
project.country=India

spring.datasource.url=jdbc:mysql://localhost:3306/student_tracker
spring.datasource.username=springstudent
spring.datasource.password=springstudent
# spring.jpa.show-sql=true
